
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  labels:
    k8s-app: kube-dns
  name: across-cluster-dns-tcp
spec:
  ports:
  - name: dns
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  type: LoadBalancer