apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidbcluster2
  namespace: hello-2
spec:
  version: v7.1.0
  timezone: UTC
  pvReclaimPolicy: Delete
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  clusterDomain: cluster.local
  acrossK8s: true
  cluster:
    name: tidbcluster1
    namespace: hello-1
    clusterDomain: cluster.local
  discovery: {}
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 1
    requests:
      storage: "10Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 1
    requests:
      storage: "10Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 1
    service:
      type: ClusterIP
    config: {}