apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  puglife.server: | 
    hello-2.svc.cluster.local:53 {
      errors
      cache 30
      forward . 20.205.255.74 {
        force_tcp
      }
    }